# GitLab CI Security Template for Agent OS
# 
# This template provides security scanning jobs that should be included
# in all GitLab CI pipelines. It runs before the build stage to catch
# security issues early in the development process.
#
# IMPORTANT: For JavaScript/Node.js projects, you MUST include the
# mandatory-javascript-supply-chain-scan.yml BEFORE this template.
#
# Usage:
# In your .gitlab-ci.yml file, include this template:
#
# For JavaScript projects:
# include:
#   - local: '.agent-os/templates/mandatory-javascript-supply-chain-scan.yml'
#   - local: '.agent-os/templates/gitlab-ci-security.yml'
#
# For non-JavaScript projects:
# include:
#   - local: '.agent-os/templates/gitlab-ci-security.yml'

stages:
  - security

# Note: For JavaScript projects, the compromised package scan is handled by
# mandatory-javascript-supply-chain-scan.yml which must be included first

# Trivy vulnerability scanner
trivy-scan:
  stage: security
  image: aquasec/trivy:latest
  script:
    - |
      echo "🔍 Running Trivy vulnerability scan..."
      trivy fs --severity HIGH,CRITICAL --exit-code 1 .
  allow_failure: false
  tags:
    - docker
  only:
    - merge_requests
    - main
    - develop

# Language-specific security scans
language-security-scan:
  stage: security
  image: node:20-bullseye
  before_script:
    - apt-get update && apt-get install -y python3 python3-pip ruby
  script:
    - |
      echo "🔍 Running language-specific security scans..."
      
      # Node.js projects
      if [ -f "package-lock.json" ]; then
        echo "📦 Running npm audit..."
        npm audit --audit-level=moderate || exit_code=$?
        if [ "${exit_code:-0}" -ne 0 ]; then
          echo "❌ npm audit found vulnerabilities"
          exit 1
        fi
      fi
      
      # Ruby projects
      if [ -f "Gemfile.lock" ]; then
        echo "💎 Running bundle audit..."
        gem install bundle-audit
        bundle audit check --update || exit_code=$?
        if [ "${exit_code:-0}" -ne 0 ]; then
          echo "❌ bundle audit found vulnerabilities"
          exit 1
        fi
      fi
      
      # Python projects
      if [ -f "requirements.txt" ] || [ -f "pyproject.toml" ]; then
        echo "🐍 Running pip-audit..."
        pip3 install pip-audit
        pip-audit || exit_code=$?
        if [ "${exit_code:-0}" -ne 0 ]; then
          echo "❌ pip-audit found vulnerabilities"
          exit 1
        fi
      fi
      
      echo "✅ Language-specific security scans completed"
  allow_failure: false
  tags:
    - docker

# Secret detection
secret-detection:
  stage: security
  image: trufflesecurity/trufflehog:latest
  script:
    - |
      echo "🔍 Scanning for exposed secrets..."
      trufflehog git file://. --only-verified --fail || exit_code=$?
      if [ "${exit_code:-0}" -eq 183 ]; then
        echo "❌ Verified secrets found in repository!"
        exit 1
      elif [ "${exit_code:-0}" -ne 0 ] && [ "${exit_code:-0}" -ne 183 ]; then
        echo "⚠️ TruffleHog scan failed with exit code: $exit_code"
        exit 1
      else
        echo "✅ No verified secrets found"
      fi
  allow_failure: false
  tags:
    - docker

# SAST (Static Application Security Testing)
sast-scan:
  stage: security
  image: returntocorp/semgrep
  script:
    - |
      echo "🔍 Running SAST scan with Semgrep..."
      semgrep --config=auto --severity=ERROR --error
  allow_failure: false
  tags:
    - docker
  only:
    - merge_requests
    - main
    - develop

# License compliance check
license-check:
  stage: security
  image: licensefinder/license_finder:latest
  script:
    - |
      echo "📜 Checking license compliance..."
      license_finder || true
      echo "ℹ️ Review license report above for compliance"
  allow_failure: true
  tags:
    - docker
  only:
    - merge_requests
    - main